exam_prep_my_music_app/albums/urls.py
from django.urls import path, include
from django.views.generic import DetailView

from exam_prep_my_music_app.albums.views import DetailAlbumView, EditAlbumView, DeleteAlbumView
from exam_prep_my_music_app.albums.views import CreateAlbumView

urlpatterns = (
    path("add/", CreateAlbumView.as_view(), name="create_album"),
    path("<int:pk>/", include([
        path("details/", DetailAlbumView.as_view(), name="details_album"),
        path("edit/", EditAlbumView.as_view(), name="edit_album"),
        path("delete/", DeleteAlbumView.as_view(), name="delete_album"),
        ])
    )
)

exam_prep_my_music_app/profiles/urls.py
from django.urls import path

from exam_prep_my_music_app.profiles.views import DetailProfileView, DeleteProfileView

urlpatterns = (
    path("details/", DetailProfileView.as_view(), name="details_profile" ),
    path("delete/", DeleteProfileView.as_view(), name="delete_profile" ),
)

exam_prep_my_music_app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('exam_prep_my_music_app.web.urls')),
    path('profiles/', include('exam_prep_my_music_app.profiles.urls')),
    path('albums/', include('exam_prep_my_music_app.albums.urls')),
]

exam_prep_my_music_app/web/urls.py
from django.urls import path
from exam_prep_my_music_app.web.views import index, create_profile

urlpatterns = (
    path('', index, name='index'),
    path("create_profile/", create_profile, name="create_profile"),

)

exam_prep_my_music_app/albums/models.py
from django.core.validators import MinValueValidator
from django.db import models

from exam_prep_my_music_app.profiles.models import Profile


class Album(models.Model):
    MAX_NAME_LENGTH = 30
    MAX_ARTIST_NAME_LENGTH = 30
    MIN_PRICE = 0.0

    name = models.CharField(
        max_length=MAX_NAME_LENGTH,
        unique=True,
        null=False,
        blank=False,
        verbose_name="Album name",
    )

    artist_name = models.CharField(
        max_length=MAX_ARTIST_NAME_LENGTH,
        null=False,
        blank=False,
        verbose_name="Artist",
    )

    genre = models.CharField(
        max_length=30,
        null=False,
        blank=False,
        choices=[
            ('Pop Music', 'Pop Music'),
            ('Jazz Music', 'Jazz Music'),
            ('R & B Music', 'R & B Music'),
            ('Rock Music', 'Rock Music'),
            ('Country Music', 'Country Music'),
            ('Dance Music', 'Dance Music'),
            ('Hip Hop Music', 'Hip Hop Music'),
            ('Other', 'Other'),
        ]
    )

    description = models.TextField(
        null=True,
        blank=True,
    )

    image_url = models.URLField(
        null=False,
        blank=False,
        verbose_name="Image URL",
    )

    price = models.FloatField(
        null=False,
        blank=False,
        validators=[
            MinValueValidator(MIN_PRICE)
        ]
    )

    owner = models.ForeignKey(
        to=Profile,
        #TODO check owner foreign key
        on_delete=models.DO_NOTHING,
    )

exam_prep_my_music_app/profiles/models.py
from django.core.exceptions import ValidationError
from django.core.validators import MinLengthValidator
from django.db import models

# Create your models here

def validate_username(username):
    is_valid = all(ch.isalnum() or ch == "_" for ch in username)
    if not is_valid:
        raise ValidationError("Ensure this value contains only letters, numbers, and underscore.")

class Profile(models.Model):
    MIN_USERNAME_LENGTH = 2
    MAX_USERNAME_LENGTH = 15


    username = models.CharField(
        max_length=MAX_USERNAME_LENGTH,
        null=False,
        blank=False,
        validators=[
            MinLengthValidator(MIN_USERNAME_LENGTH),
    ])

    email = models.EmailField(
        null=False,
        blank=False,
    )

    age = models.PositiveIntegerField(
        null=True,
        blank=True,
    )

exam_prep_my_music_app/web/models.py
from django.db import models

# Create your models here.

exam_prep_my_music_app/web/forms.py
from django import forms

from exam_prep_my_music_app.profiles.models import Profile


class CreateProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('username', 'email', 'age')

        widgets = {
            'username': forms.TextInput(
                attrs={
                    'placeholder': 'Username'}),
            'email': forms.EmailInput(
                attrs={
                    'placeholder': 'Email'}),
            'age': forms.NumberInput(
                attrs={
                    'placeholder': 'Age'}),
        }

exam_prep_my_music_app/albums/views.py
from django.forms import modelform_factory
from django.shortcuts import render
from django.template.base import kwarg_re
from django.urls import reverse_lazy
from django.views.generic import CreateView, DetailView, UpdateView, DeleteView
from exam_prep_my_music_app.albums.models import Album
from exam_prep_my_music_app.web.views import get_profile


# Create your views here.

class AlbumFormViewMixin:
    def get_form(self, form_class=None):
        form = super().get_form(form_class=form_class)
        # Can be moved to mixin
        form.fields["name"].widget.attrs["placeholder"] = "Album Name"
        form.fields["artist_name"].widget.attrs["placeholder"] = "Artist"
        form.fields["description"].widget.attrs["placeholder"] = "Description"
        form.fields["image_url"].widget.attrs["placeholder"] = "Image URL"
        form.fields["price"].widget.attrs["placeholder"] = "Price"

        return form

class ReadonlyViewMixin:
    def get_form(self, form_class=None):
        form = super().get_form(form_class=form_class)

        for field in form.fields.values():
            field.widget.attrs["readonly"] = "readonly"

        return form





class CreateAlbumView(AlbumFormViewMixin, CreateView):
    queryset = Album.objects.all()
    fields = ('name', 'artist_name', 'genre', 'description', 'image_url', 'price')
    template_name = "albums/album-add.html"
    success_url = reverse_lazy("index")




    # TODO: Check for better solution.Working OK
    def form_valid(self, form):
        form.instance.owner_id = get_profile().pk

        return super().form_valid(form)


class DetailAlbumView(DetailView):
    queryset = Album.objects.all()
    template_name = "albums/album-details.html"


class EditAlbumView(AlbumFormViewMixin, UpdateView):
    queryset = Album.objects.all()
    fields = ('name', 'artist_name', 'description', 'image_url', 'price')
    template_name = "albums/album-edit.html"
    success_url = reverse_lazy("index")

class DeleteAlbumView(ReadonlyViewMixin, DeleteView):
    queryset = Album.objects.all()
    fields = ('name', 'artist_name', 'description', 'image_url', 'price')
    template_name = "albums/album-delete.html"
    success_url = reverse_lazy("index")
    form_class = modelform_factory(Album, fields=('name', 'artist_name', 'genre', 'description', 'image_url', 'price'))

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs["instance"] = self.object
        return kwargs

exam_prep_my_music_app/profiles/views.py
from django.shortcuts import render
from django.views import generic as views

from exam_prep_my_music_app.profiles.models import Profile
from exam_prep_my_music_app.web.views import get_profile


class DetailProfileView(views.DetailView):
    queryset = Profile.objects.all()
    template_name = "profiles/profile-details.html"
    fields = "__all__"

    # TODO extract to different module
    def get_profile():
        return Profile.objects.first()

    def get_object(self, queryset=None):
        return get_profile()


class DeleteProfileView(views.DeleteView):
    pass

exam_prep_my_music_app/web/views.py
from django.shortcuts import render, redirect
from django.views import generic as views

from exam_prep_my_music_app.albums.models import Album
from exam_prep_my_music_app.profiles.models import Profile
from exam_prep_my_music_app.web.forms import CreateProfileForm


# Create your views here.


def get_profile():
    return Profile.objects.first()

def create_profile(request):
    form = CreateProfileForm(request.POST or None)

    if form.is_valid():
        form.save()
        return redirect("index")

    context = {
        'form': form,
    }
    return render(request, "web/home-no-profile.html", context)


def index(request):
    profile = get_profile()

    if profile is None:
        return create_profile(request)

    context = {
        "albums": Album.objects.all(),
    }

    return render(request, "web/home-with-profile.html", context)










# class IndexView(views.TemplateView):
#     def get_template_names(self):
#         if get_profile() is None:
#             return ["web/home-no-profile.html"]
#         return ["web/home-with-profile.html"]

templates/albums/album-add.html
{% extends 'base.html' %}

{% block main_content %}
    <!-- Main Content -->
    <!--Create Page-->
    <section class="createPage">
    <form action="{% url 'create_album' %}" method="POST">
      <fieldset>
        <legend>Add Album</legend>
        <div class="container">
          <!-- Form for Adding Album -->
            {{ form }}
            
          <!-- Button for Adding Album -->
          <button class="add-album" type="submit">Add New Album</button>
            {% csrf_token %}
            
        </div>
      </fieldset>
    </form>
    </section>
{% endblock %}

templates/albums/album-delete.html
{% extends 'base.html' %}

{% block main_content %}
  <!-- Main Content -->
  <!--Delete Page-->
  <section class="editPage">
    <form method="POST" action="{% url "delete_album" pk=object.pk %}">
      <fieldset>
          <legend>Delete Album</legend>
          <div class="container">
            {% csrf_token %}
            {{ form }}
          <!-- Button for Deleting an Album -->
          <button class="delete-album" type="submit">Delete Album</button>
          </div>
      </fieldset>
    </form>
  </section>
  
{% endblock %}

templates/albums/album-details.html
{% extends "base.html" %}

{%  block main_content %}
      <!-- Main Content -->
      <!--Details Page-->
      <section id="detailsPage">
        <div class="wrapper">
          <div class="albumCover">
            <!-- Album Image -->
            <img src="{{ object.image_url }}" alt="{{ object.description}}" />
          </div>

          <div class="albumInfo">
            <div class="albumText">
              <!-- Album Info -->
              <h1>Name: {{ object.name }}</h1>
              <h3>Artist: {{ object.artist_name }}</h3>
              <h4>Genre: {{ object.genre }}</h4>
              <h4>Price: ${{ object.price|floatformat:2 }}</h4>
              <p>
                Description: {{ object.description}}
              </p>
            </div>

            <div class="actionBtn">
              <!-- Album Buttons -->
               
              <a href="{% url "edit_album" pk=object.pk  %}" class="edit">Edit</a> 
                {# TODO: fix this links #}
              <a href="{% url "delete_album" pk=object.pk %}" class="remove">Delete</a>
            </div>
          </div>
        </div>
      </section>
{% endblock %}

templates/albums/album-edit.html
{% extends 'base.html' %}

{% block main_content %}
  <!-- Main Content -->
  <!--Edit Page-->
  <section class="editPage">
    <form method="POST" action="{% url 'edit_album' pk=object.pk %}" >
      <fieldset>
          <legend>Edit Album</legend>
        {% csrf_token %}
        {{ form }}
        <!-- Button for Editing Album -->
        <button class="edit-album" type="submit">Edit Album</button>
       
      </fieldset>
    </form>
  </section>

{% endblock %}

templates/base.html
{% load static%}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>My Music App</title>
    <!-- Static Load -->
    <link rel="stylesheet" href="{%  static '/css/style.css' %}" />
  </head>

  <body>
    <div id="box">
      <!-- Navigation Bar -->
      <header>
        <nav>
          <img src="{% static '/images/headphones.png' %}" alt="headphones" />
          <a href="{% url "index" %}">Home</a>
          <ul></ul>
          <ul>
            <!--Only for user with created profile-->
            <li><a href="{% url 'create_album' %}">Create Album</a></li>
            <li><a href="{% url "details_profile" %}">Profile</a></li>
          </ul>
        </nav>
      </header>
      <!-- End Navigation Bar -->
        
        {% block main_content %}
        
        
        {% endblock %}
      <!-- Footer -->
      <footer>
        <div>&copy;SoftUni Team 2024. All rights reserved.</div>
      </footer>
      <!-- End Footer -->
    </div>
  </body>
</html>

templates/profiles/profile-delete.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>My Music App</title>
    <!-- Static Load -->
    <link rel="stylesheet" href="/css/style.css" />
  </head>

  <body>
    <div id="box">
      <!-- Navigation Bar -->
      <header>
        <nav>
          <img src="/images/headphones.png" alt="headphones" />
          <a href="#">Home</a>
          <ul></ul>
          <ul>
            <!--Only for user with created profile-->
            <li><a href="#">Create Album</a></li>
            <li><a href="#">Profile</a></li>
          </ul>
        </nav>
      </header>
      <!-- End Navigation Bar -->

      <!-- Main Content -->
      <!-- Delete Profile Page-->
      <section id="detailsPage">
        <div class="wrapper">
          <div class="profileText">
            <!-- Delete Profile Form -->
            <h1>Are you sure you want to delete your profile?</h1>
            <form>
              <!-- Confirm Button -->
              <button class="delete-profile" type="submit">Delete</button>
            </form>
            <!-- End Delete Profile Form -->
          </div>
        </div>
      </section>
      <!-- Footer -->
      <footer>
        <div>&copy;SoftUni Team 2024. All rights reserved.</div>
      </footer>
      <!-- End Footer -->
    </div>
  </body>
</html>

templates/profiles/profile-details.html
{% extends 'base.html' %}

{% block main_content %}

  <!-- Main Content -->
  <!--Details Page-->
  <section id="detailsPage">
    <div class="wrapper">
      <div class="profilePage">
        <img
          src="https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_960_720.png"
          alt="Profile Image"
        />
      </div>

      <div class="profileText">
        <!-- Profile Info -->
        <h1>Username: {{ object.username }}</h1>
        <h1>Email: {{ object.email}}</h1>
          {% if object.age %}
            <h1>Age: {{ object.age }}</h1>
          {% endif %}
        
        <h1>Albums: {{ object.album_set.count }}</h1>
      </div>

      <div class="actionBtn">
        <!-- Button for Deleting the Profile -->
        <a href="{% url "delete_profile" %}" class="remove">Delete</a>
      </div>
    </div>
  </section>
  
{% endblock %}

templates/web/home-no-profile.html
{% extends 'base.html' %}
{% load static %}
{% block main_content %}

      <!-- Main Content -->
      <!--Home Page-->
      <div class="container-inline">
        <section id="welcomePage">
          <div id="welcome-message">
            <h1>Welcome to</h1>
            <h1>My Music App!</h1>
          </div>
          <div class="music-img">
            <img src="{% static '/images/musicIcons.webp' %}" alt="music-icon" />
          </div>
        </section>

        <!-- Registration -->
        <section id="registerPage">
          <form method="POST" action="{% url "create_profile" %}">
            <fieldset>
              <legend>Profile</legend>
              <!-- Form for Registration -->
              {{ form }}
              {% csrf_token %}
              <!-- Button to Create Profile -->
              <button type="submit" class="register">Enter</button>
            </fieldset>
          </form>
        </section>
      </div>

{% endblock %}
      

templates/web/home-with-profile.html
{% extends 'base.html' %}
{% block main_content %}

      <!-- Main Content -->
      <!-- Catalog with Albums-->
      <section id="catalogPage">
      {%  if albums %}
           <h1>All Albums</h1>
      {% else %}
           <p>No Albums in Catalog!</p>
      {% endif %}
                
      {% for album in albums %}
        <!-- Card-Box in catalog -->
        <div class="card-box">
          <img src="{{  album.image_url }}" alt="{{ album.description}}" />
          <div>
            <div class="text-center">
              <p class="name">Name: {{ album.name}}</p>
              <p class="artist">Artist: {{ album.artist_name}}</p>
              <p class="genre">Genre: {{ album.genre }}</p>
              <p class="price">Price: ${{ album.price|floatformat:2 }}</p>
            </div>
            <div class="btn-group">
              <a href="{% url "details_album" pk=album.pk %}">Details</a>
            </div>
          </div>
        </div>
        <!-- End Card-Box in catalog -->
      {% endfor %}
      
      
      <div class="alert alert-warning" role="alert"></div>
      </section>
{% endblock %}